# WEEK 4: NUMPY #

### Question 1: ###

In [1]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

a_b = np.intersect1d(a,b) #finds distinct and unique items in array a and b and outputs it as a_b array
print(a_b)

[2 4]


### Question 2: ###

In [2]:
myarray1 = np.arange(1,16).reshape((3,5)).T #creates a sequenced array from 1 to 15 and transposes it to become a 5x3 array
print(myarray1)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### Question 3: ###

In [3]:
a = np.array([12,5,7,15,3,1,8])
b = np.array([14,6,3,11,19,12,5])

a = np.setdiff1d(a,b) #removes items in array a that are present in item b
print(a)

[ 1  7  8 15]


### Question 4: ###

**Printing My Cumulative Miles Array:**

In [4]:
myrandom = np.random.randint(40,60,35) #randomly generates 35 integers between 40 and 60 and stores it as an array object
myrandomlist = myrandom.tolist() #converts array into a list

om_reading = [] #creates an empty list of cumulative odometer reading
totalmiles = 0
for x in range(35):
    if x > 0 and x % 8 == 0: #checks if x is greater than zero and if it is divisible by 8
        om_reading.append(totalmiles) #if divisible by 8 copies the same odometer reading
    else: 
        totalmiles += myrandomlist[x] 
        if x != 34 and totalmiles <= 1551: 
            om_reading.append(totalmiles) #appends cumulative sum on the list if condition is satisfied
        else:
            om_reading.append(1551) #forces the last element to be equal to become total distance between nyc and key west,fl

om_reading = np.asarray(om_reading) #converts list into an array
print(om_reading)

[  44   99  153  212  265  316  361  417  417  474  525  574  622  664
  706  746  746  787  836  883  925  971 1014 1072 1072 1123 1171 1224
 1279 1336 1378 1418 1418 1476 1551]


**Printing My Miles Covered Per Day:**

In [5]:
miles_per_day = np.diff(om_reading)
print(miles_per_day)

[55 54 59 53 51 45 56  0 57 51 49 48 42 42 40  0 41 49 47 42 46 43 58  0
 51 48 53 55 57 42 40  0 58 75]


**Approach to Problem:**

For this problem, I decided to create the array of the odometer reading to be created programatically. To do so, the following steps were done:
1. Research on total miles between NYC to Key West, Florida by bike. Found this to be equal to 1,551 miles.
2. Divided total miles (1551) by 35 days since it is said that I will be arriving at my destination on the 35th day. This was found to be equal to around 44.31 days.This information was used to generate random numbers. This is the reason why the random numbers generated was decided to be between 40 and 60.
3. For the 4 non consecutive days that I did not do anything, 35 days was divided by 4. Since this is equal to 8, it was decided that I will take a rest every 8th day. Therefore, this was incorporated on the code such that if it is the 8th, 16th, 24th, and 32nd day, my odometer reading will not change.
4. Lastly, on the 35th day, the code forces the array to have the total miles, that is, 1551.

**Use of Numpy:**
Numpy was first used to generate random integer numbers between 40 and 60 and also with a size of 35. List was created to store odometer reading and later on this list was converted back into an array using numpy. Lastly, numpy was used to create a new array that prints out the total miles covered each day.

### Question 5: ###

**Initialization:**

In [6]:
import pandas
# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

C:\Users\mhari\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

**Answers to Questions:**

In [7]:
max_gallons = np.max(nyc_water[:,2]) #calculates maximum of all rows in 3rd column (yearly water consumption)
num_cal_year = np.size(nyc_water,axis=0) #gets number of elements columnwise
mean_percapwater = np.mean(nyc_water[:,3]) #calculates mean of all rows in 4th column (per capita water consumption in NYC)
std_percapwater = np.std(nyc_water[:,3]) #calculates standard deviation of all rows in 4th column (per capita water consumption in NYC)
print('The maximum yearly consumption of water in NYC in millions of gallons per day is: ' + format(max_gallons))
print('The number of calendar years represented within the data set is: ' + format(num_cal_year) + ' years.')
print('The per capita water consumption mean is: ' + str(mean_percapwater) + ' while standard deviation is: ' + str(std_percapwater))

The maximum yearly consumption of water in NYC in millions of gallons per day is: 1512.0
The number of calendar years represented within the data set is: 39 years.
The per capita water consumption mean is: 160.30769230769232 while standard deviation is: 31.51894330370624


In [8]:
nyc_pop = nyc_water[:,1] #creates a new array to store population data
pop_diff = np.diff(nyc_pop) #calculates difference per year and stores it in a new array
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
